name: Update vv ita world
on:
  schedule:
    - cron: '0 */6 * * *'  # Esegue ogni 6 ore
  workflow_dispatch:  # Permette di eseguire manualmente

permissions:
  contents: write  # Permette di fare commit e push nel repository

jobs:
  run-script:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    
    steps:
      - name: Checkout del repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Modificato da 1 a 0 per ottenere la storia completa
      - name: Imposta Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Sostituisci con la versione necessaria

      - name: Installa le dipendenze
        run: pip install requests

      - name: Esegui lo script
        run: |
          python def.py
          python vvworld.py
          
      - name: Commit and push changes
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          
          # Aggiunto pull con rebase per incorporare modifiche recenti
          git pull --rebase origin main
          
          # Aggiunto controllo per committare solo se ci sono modifiche
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Update vv ita and world $(date +%H:%M)"
            git push
          else
            echo "No changes to commit"
          fi
