name: Update world 24 7

on:
  schedule:
    - cron: "0 */4 * * *" # ogni lunedi alle 3
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    
    steps:
      - name: Checkout repository (no history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install requests pytz
          pip install bs4
          pip install chardet
          
      - name: Run EPG grabber script
        env:
          M3U4U_EPG: ${{ secrets.M3U4U_EPG }}
        run: |
          rm -f daddyliveSchedule.json
          rm -f 247channels.html
          rm -f 247world.m3u8
          rm -f 247world.xml
          python 247world.py
          
      - name: Commit and push changes
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          
          # Stage all changes first
          git add .
          
          # Check if there are changes to commit
          if [[ -n $(git status --porcelain) ]]; then
            # Commit changes before pulling
            git commit -m "Update world247 $(date +%H:%M)"
            
            # Try to pull with rebase, but force push if it fails
            if ! git pull --rebase origin main; then
              echo "Rebase failed, using force push instead"
              git push --force
            else
              git push
            fi
          else
            echo "No changes to commit"
          fi